# fly.toml app configuration file generated for techblog-black-pond-8807 on 2025-01-30T11:15:53+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'techblog-black-pond-8807'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
